name: Deployment

on:
  push:
    branches: [main]

concurrency: production

jobs:
  deployment:
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://mutecipher.com

    env:
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      MRSK_REGISTRY_PASSWORD: ${{ secrets.MRSK_REGISTRY_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install MRSK
        run: gem install mrsk

      - name: Deploy site
        run: mrsk deploy
